config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :dreams do
    resources :sleeps, only: [ :new, :create ]
    resources :reviews, except: :destroy
  end
  resources :users, only: :show

  resources :reviews, only: :destroy
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dream.rb
class Dream < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :sleeps, dependent: :destroy
  mount_uploader :photo, PhotoUploader

  include PgSearch
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :dream
  validates :accuracy, inclusion: { in: 0..10 } #message: "Please give put a score from 0-10"
  validates :design, inclusion: { in: 0..10 } #message: "Please give put a score from 0-10"
  validates :value, inclusion: { in: 0..10 } #message: "Please give put a score from 0-10"

  def rating
    (value + design + accuracy) / 3
  end

end

app/models/sleep.rb
class Sleep < ApplicationRecord
  belongs_to :user
  belongs_to :dream
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dreams, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :sleeps, dependent: :destroy
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :set_dream, only: [:show, :edit, :update, :destroy]

  def index         # GET /dreams
    if params[:query].present?
      @dreams = Dream.search_by_name_and_description(params[:query])
    else
      @dreams = Dream.all
    end
  end

  def show          # GET /dreams/:id
    @sleep = Sleep.new
    @review = Review.new
    @reviews = @dream.reviews
  end

  def new           # GET /dreams/new
    @dream = Dream.new
  end

  def create        # POST /dreams
    @dream = Dream.new(dream_params)
    @dream.user = current_user
    if @dream.save
      redirect_to dream_path(@dream)
    else
      raise
      render :new
    end
  end

  def edit          # GET /dreams/:id/edit
  end

  def update        # PATCH /dreams/:id
    @dream.update(dream_params)
    redirect_to dream_path(@dream)
  end

  def destroy       # DELETE /dreams/:id
    @dream.destroy
    redirect_to dreams_path
  end

  private

  def set_dream
    @dream = Dream.find(params[:id])
  end

  def dream_params
    params.require(:dream).permit(:name, :category, :price, :description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
    @dreams = Dream.first(3)
    @dreams_critics_choice = Dream.all.sort_by {|dream| dream.reviews.map {|review| review.rating }.sum / dream.reviews.size }
    @dreams_latest = Dream.last(3)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index         # GET /reviews
    @reviews = Review.all
  end

  def show
    @dream = Dream.find(params[:dream_id])
  end

  def new           # GET /reviews/new
    @review = Review.new
    @dream = Dream.find(params[:dream_id])
  end

  def create        # POST /reviews
    @review = Review.new(review_params)
    @review.user = current_user
    @review.dream = Dream.find(params[:dream_id])
    @dream = Dream.find(params[:dream_id])
    if @review.save
      redirect_to dream_path(@dream)
    else
      render :new
    end
  end

  def edit          # GET /reviews/:id/edit
    @dream = Dream.find(params[:dream_id])
    @review = Review.find(params[:id])
  end

  def update        # PATCH /reviews/:id
    @dream = Dream.find(params[:dream_id])
    @review.update(review_params)
    redirect_to dream_path(@dream)
  end

  def destroy      # DELETE /reviews/:id
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to dream_path(@review.dream)
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :accuracy, :value, :design)
  end
end

app/controllers/sleeps_controller.rb
class SleepsController < ApplicationController
  before_action :set_dream
  before_action :set_sleep, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    # we need @dream in our `simple_form_for`
    @sleep = Sleep.new
  end

  def create
    @sleep = Sleep.new(sleep_params)
  # we need `dream_id` to asssociate sleep with corresponding dream
    @sleep.dream = @dream
    @sleep.user = current_user
    if @sleep.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @sleep.update(sleep_params)
    redirect_to sleep_path(@sleep)
  end

  def destroy
    @sleep.destroy
    redirect_to sleep_path
  end

  private

  def set_dream
    @dream = Dream.find(params[:dream_id])
  end

  def set_sleep
    @sleep = Sleep.find(params[:id])
  end

  def sleep_params
    params.require(:sleep).permit(:date, :dream_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @sleeps = @user.sleeps
    @reviews = @user.reviews
    @photo = @user.photo
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    request.path == test_path ? "active" : "nav-item"
  end
end

app/views/dreams/_form.html.erb
<div class ="container forms-font-colour forms-container">
  <%= simple_form_for(@dream) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :category %>
      <%= f.text_field :category, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
    </div>

    <%= f.submit class: 'btn btn-ghost' %>
  <% end %>
</div>

app/views/dreams/edit.html.erb
<div class="container">
  <%= render 'form', dream: @dream %>
</div>

app/views/dreams/index.html.erb
<div class="background-container">

<div class="hero">
<h1>The Dream Repertoire</h1>
</div>
<br>
<div class="search">
<%= form_tag dreams_path, class: "search-form", method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "search-box",
    placeholder: "Find a dream"
  %>
  <%= submit_tag "Search", class: "search-button" %>
  <% end %>
</div>
<div class="container">
  <div class="dreams-list">
    <% @dreams.each do |dream| %>

        <div class="dream" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)),
         url('<%= cl_image_path dream.photo, crop: :fill %>')">
          <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
            <h3><%= link_to(dream.name, dream_path(dream)) %></h3>
            <p><%= dream.description.split.first(10).join(' ') %>...</p>
          <!-- <div class="card-footer">
          </div> -->
        </div>

    <% end %>
</div>
</div>
</div>

app/views/dreams/new.html.erb
<div class="container">
<h2 style="padding-left: 20vw;">Create a new dream</h2>
  <%= render 'form', dream: @dream %>
</div>

app/views/dreams/show.html.erb
<div class="dreams-show-background">
  <div class="container">
    <h1 class="show-font-colour" style="padding-top: 2vh;"><%= @dream.name %></h1>
    <hr />
    <div class="row">
      <div class="col-sm-12 col-md-8 details-section">
        <%= cl_image_tag @dream.photo, height: 400, width: 600 %>
        <div class="d-flex dream-detail">
          <ul class="detail-list">
            <li><strong>Category:</strong> <%= @dream.category %></li>
            <li><strong>Price:</strong> <%= @dream.price %></li>
          </ul>
        </div>
        <div class="dream-description">
          <h2 class="show-font-colour"><strong>Description:</strong></h2>
          <p><%= @dream.description %></p>
        </div>
        <br>
        <div class="d-flex show-font-colour">
          <h3>Reviews</h3>
          <div class="ml-auto stick-to-screen">
            <%= link_to "Write a review", new_dream_review_path(@dream), class: "btn btn-ghost" %>
          </div>
        </div>
        <hr />
          <div>
            <% @reviews.each do |review| %>
            <div class="review-card">
              <%= cl_image_tag review.user.photo, width: 200, height: 200, crop: :thumb, gravity: :face %>
              <div class="review-card-infos">
                <h2><%= review.content %></h2>
                <div class="d-flex justify-content-between">
                  <p><strong>Accuracy:</strong> <%= review.accuracy %> <strong>Design:</strong>  <%= review.design %> <strong>Value:</strong>  <%= review.value %> <strong>Overall Rating:</strong>  <%= review.rating %></p>
                  <%= link_to "Edit Review", edit_dream_review_path(@dream, review), class: "review-card-edit btn btn-ghost" %>
                </div>
              </div>
            </div>
            <% end %>
          </div>
      </div>
      <div class="col-sm-12 col-md-4">
        <div class="card sleep-booking-form">
          <%= render 'sleeps/form' %>
        </div>
      </div>
    </div>
    <div class="d-flex">
      <div class="dream-show-button-bottom">
        <%= link_to "Back", dreams_path, class: "btn btn-ghost" %>
      </div>
      <div class="dream-show-button-bottom">
        <%= link_to "Edit Dream", edit_dream_path(@dream), class: "btn btn-ghost" %>
      </div>
      <div class="dream-show-button-bottom">
        <%= link_to "Delete Dream", dream_path(@dream),
              method: :delete,
              data: { confirm: "Are you sure?" }, class: "btn btn-ghost" %>
      </div>
    </div>
    <br>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dreamrunner - Rent your dreams</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <!-- app/views/layouts/application.html.erb -->
  <%= render 'shared/navbar' %>
  <div style="min-height: calc(100vh - 60px)">
    <%= yield %>
  </div>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1538370965046-79c0d6907d47?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80);">
  <div class="container">
    <div class="home-head">
    <h1>Escapism for the masses</h1>
    </div>
  </div>
</div>

<div class="container">
  <h2>Some of our favourites</h2>
  <div class="cards">
    <% @dreams.each do |dream| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path dream.photo, height: 300, width: 400, crop: :fill %>')">
        <%= link_to dream.name, dream_path(dream) %>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <h2>Latest dreams</h2>
  <div class="cards">
    <% @dreams_latest.each do |dream| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path dream.photo, height: 300, width: 400, crop: :fill %>')">
        <%= link_to dream.name, dream_path(dream) %>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <h2>Dreams picked by critics</h2>
  <% @dreams_critics_choice.first(3).each do |dream| %>
    <div class="card-product">
      <img src="<%= cl_image_path dream.photo %>">
      <div class="card-info">
        <h2><%= link_to dream.name, dream_path(dream) %></h2>
        <p><%= dream.description %></p>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_form.html.erb
<div class="container forms-font-colour">
  <%= simple_form_for [@dream, @review] do |f| %>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :accuracy %>
      <%= f.number_field :accuracy, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :design %>
      <%= f.number_field :design, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :value %>
      <%= f.number_field :value, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-ghost' %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <%= render 'form', review: @review, dream: @dream %>
        <%= link_to "Delete review", review_path(@review),
            method: :delete,
            data: { confirm: "Are you sure?" }, class: "btn btn-ghost mt-3 ml-3" %>
     </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container forms-container">
  <h2>Write a review</h2>
  <%= render 'form', review: @review, dream: @dream %>
</div>

app/views/reviews/show.html.erb
<h2><%= @review.dream.name %></h2>
<br>
<p>Content: <%= @review.content %></p>
<p>Accuracy: <%= @review.accuracy %></p>
<p>Design: <%= @review.design %></p>
<p>Value: <%= @review.value %></p>
<p>Overall rating: <%= @review.rating %></p>


<%= link_to "Edit", edit_dream_review_path(@dream, @review) %>
<br>
<%= link_to "Delete", review_path(@review),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
<br>
<%= link_to "Back", dreams_path %>
<br>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/lewagon"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/lewagonlondon/?hl=en"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/lewagonlondon/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/lewagonlondon?lang=en"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/school/le-wagon/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Copyright Dreamrunner 2019.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
   <h3 class="logo-font">Dreamrunner</h3>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class=<%= current_class?(root_path) %>>
          <%= link_to "Home", root_path, class: "link-colour nav-link" %>
        </li>
        <li class=<%= current_class?(dreams_path) %>>
          <%= link_to "Find your dream", dreams_path, class: "link-colour nav-link" %>
        </li>
        <li class=<%= current_class?(new_dream_path) %>>
          <%= link_to "Host a dream", new_dream_path, class: "nav-link link-colour" %>
        </li>
        <li class="nav-item">
          <%= link_to "Upcoming dreams", user_path(current_user), class: "nav-link link-colour" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, width: 40, height: 40, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle image-shade", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link link-colour" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/sleeps/_form.html.erb
<div class="container forms-font-colour">
  <%= simple_form_for [@dream, @sleep] do |f| %>
    <%= f.input :date %>
    <%= f.submit "Add a sleep booking", class: "btn btn-ghost" %>
  <% end %>
</div>

app/views/sleeps/new.html.erb
<%= render 'form', dream: @sleep %>

app/views/users/show.html.erb
<div class="user-container">
  <div class="main-section">
    <div class="dreams">
      <h2>Upcoming Dreams</h2>
      <% @sleeps.each do |sleep| %>
        <div class="card-product">
          <%= cl_image_tag sleep.dream.photo, height: 300, width: 400, crop: :fill %>
          <div class="card-product-infos">
            <h3><%= sleep.dream.name %></h3>
            <p><%= sleep.dream.description %></p>
            <p>Date: <%= sleep.date %></p>
          </div>
        </div>
      <% end %>
    </div>
    <h2>My Reviews</h2>
    <div class="reviews">
      <% @reviews.each do |review| %>
        <div class="card-product" id="reviews">
          <div class="card-product-infos">
            <h5><%= review.dream.name %></h5>
            <h4><%= review.content %></h4>
            <div class="ratings">
              <p>Accuracy: <%= review.accuracy %></p>
              <p>Value: <%= review.value %></p>
              <p>Design: <%= review.design %></p>
            </div>
            <h5>Overall: <%= review.rating %></h5>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div id="ideogram">
    <%= image_tag "ideogram.jpg", alt: "Indulge", width: 200 %>
  </div>
</div>